### ISSUE TITLE
 Unrecognized type (component dependency?) is present

### ISSUE THREAD

**Issue by mironoff2007** [yandex/yatagan#70]
I'm using api same as dagger. I had such errors.
Please advise. Am I using it incorrectly?
How to inject dependencies to graph?

![image](https://github.com/yandex/yatagan/assets/18057056/e837961c-d20d-44c7-a624-b71330bcb96d)

![image](https://github.com/yandex/yatagan/assets/18057056/5f6ecb3c-f2a3-4914-addd-ef40e1744895)

**Comment by Jeffset** [comment]
Well, in your code you extend the `Builder` interface with the `AppComponent` interface. That's why the method `fun inject(activity: MyActivity)` gets into the `Builder` and confuses the framework, as it makes no sense inside a component builder. In Dagger you'd get similar error message.

To my understanding, there's little sense in extending the builder interface with the component interface it tries to build. If you did that deliberately, please describe what you meant by doing so. Otherwise, just remove the `: AppComponent`, and you should be all good.

**Comment by mironoff2007** [comment]
Thank you. This is my fault.
